name: pre-commit

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Set up system
              run: |
                  wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
                  sudo chmod a+x php-cs-fixer
                  sudo mv php-cs-fixer /usr/local/bin/php-cs-fixer
                  wget https://github.com/phpstan/phpstan-shim/raw/master/phpstan.phar -O phpstan.phar
                  sudo chmod a+x phpstan.phar
                  sudo mv phpstan.phar /usr/local/bin/phpstan
                  wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -O phpcs.phar
                  sudo chmod a+x phpcs.phar
                  sudo mv phpcs.phar /usr/local/bin/phpcs
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pre-commit
            - name: Load cache for pre-commit
              uses: actions/cache@v2
              with:
                  path: ~/.cache/pre-commit
                  key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pre-commit-
            - name: Run pre-commit
              run: |
                  pre-commit run --show-diff-on-failure --color=always --all-files
              env:
                  SKIP: build
